// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// Contains metadata about how much money a recommendation can save or incur.
public struct CostProjection: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// An approximate projection on amount saved or amount incurred. Negative cost
  /// units indicate cost savings and positive cost units indicate increase.
  /// See google.type.Money documentation for positive/negative units.
  ///
  /// A user's permissions may affect whether the cost is computed using list
  /// prices or custom contract prices.
  public var cost: GoogleType.Money? = nil

  /// Duration for which this cost applies.
  public var duration: GoogleCloudWKT.Duration? = nil

  /// The approximate cost savings in the billing account's local currency.
  public var costInLocalCurrency: GoogleType.Money? = nil

  /// Initialize a new instance of `CostProjection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CostProjection().with { $0.cost = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.v1.CostProjection"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
