// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Contains the impact a recommendation can have for a given category.
public struct Impact: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Category that is being targeted.
  public var category: Impact.Category = Impact.Category()

  /// The service that this impact is associated with.
  public var service: Swift.String = Swift.String()

  /// Contains projections (if any) for this category.
  public var projection: OneOf_Projection? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Impact`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Impact().with { $0.category = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let category = CodingKeys(stringValue: "category")
    static let costProjection = CodingKeys(stringValue: "costProjection")
    static let securityProjection = CodingKeys(stringValue: "securityProjection")
    static let sustainabilityProjection = CodingKeys(stringValue: "sustainabilityProjection")
    static let reliabilityProjection = CodingKeys(stringValue: "reliabilityProjection")
    static let service = CodingKeys(stringValue: "service")

    static let _knownKeys: Set<Swift.String> = [
      "category",
      "costProjection",
      "securityProjection",
      "sustainabilityProjection",
      "reliabilityProjection",
      "service",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Impact.Category.self, forKey: .category) {
      self.category = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .service) {
      self.service = value
    }

    var projection: OneOf_Projection? = nil
    let projectionCheckAndSet = {
      if projection != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'projection'"))
      }
      projection = $0
    }
    if let costProjection = try container.decodeIfPresent(
      CostProjection?.self, forKey: .costProjection)
    {
      try projectionCheckAndSet(.costProjection(costProjection))
    }
    if let securityProjection = try container.decodeIfPresent(
      SecurityProjection?.self, forKey: .securityProjection)
    {
      try projectionCheckAndSet(.securityProjection(securityProjection))
    }
    if let sustainabilityProjection = try container.decodeIfPresent(
      SustainabilityProjection?.self, forKey: .sustainabilityProjection)
    {
      try projectionCheckAndSet(.sustainabilityProjection(sustainabilityProjection))
    }
    if let reliabilityProjection = try container.decodeIfPresent(
      ReliabilityProjection?.self, forKey: .reliabilityProjection)
    {
      try projectionCheckAndSet(.reliabilityProjection(reliabilityProjection))
    }
    self.projection = projection
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.category, forKey: .category)
    try container.encode(self.service, forKey: .service)

    if let choice = self.projection {
      switch choice {
      case .costProjection(let value):
        try container.encode(value, forKey: .costProjection)
      case .securityProjection(let value):
        try container.encode(value, forKey: .securityProjection)
      case .sustainabilityProjection(let value):
        try container.encode(value, forKey: .sustainabilityProjection)
      case .reliabilityProjection(let value):
        try container.encode(value, forKey: .reliabilityProjection)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The category of the impact.
  public enum Category: Codable, Equatable, Sendable {
    /// Default unspecified category. Don't use directly.
    case unspecified
    /// Indicates a potential increase or decrease in cost.
    case cost
    /// Indicates a potential increase or decrease in security.
    case security
    /// Indicates a potential increase or decrease in performance.
    case performance
    /// Indicates a potential increase or decrease in manageability.
    case manageability
    /// Indicates a potential increase or decrease in sustainability.
    case sustainability
    /// Indicates a potential increase or decrease in reliability.
    case reliability
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cost: return 1
      case .security: return 2
      case .performance: return 3
      case .manageability: return 4
      case .sustainability: return 5
      case .reliability: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CATEGORY_UNSPECIFIED"
      case .cost: return "COST"
      case .security: return "SECURITY"
      case .performance: return "PERFORMANCE"
      case .manageability: return "MANAGEABILITY"
      case .sustainability: return "SUSTAINABILITY"
      case .reliability: return "RELIABILITY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Category/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CATEGORY_UNSPECIFIED": self = .unspecified
      case "COST": self = .cost
      case "SECURITY": self = .security
      case "PERFORMANCE": self = .performance
      case "MANAGEABILITY": self = .manageability
      case "SUSTAINABILITY": self = .sustainability
      case "RELIABILITY": self = .reliability
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Category/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cost
      case 2: self = .security
      case 3: self = .performance
      case 4: self = .manageability
      case 5: self = .sustainability
      case 6: self = .reliability
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CATEGORY_UNSPECIFIED")
      case .cost: return try container.encode("COST")
      case .security: return try container.encode("SECURITY")
      case .performance: return try container.encode("PERFORMANCE")
      case .manageability: return try container.encode("MANAGEABILITY")
      case .sustainability: return try container.encode("SUSTAINABILITY")
      case .reliability: return try container.encode("RELIABILITY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Contains projections (if any) for this category.
  public enum OneOf_Projection: Codable, Equatable, Sendable {
    /// Use with CategoryType.COST
    indirect case costProjection(CostProjection?)
    /// Use with CategoryType.SECURITY
    indirect case securityProjection(SecurityProjection?)
    /// Use with CategoryType.SUSTAINABILITY
    indirect case sustainabilityProjection(SustainabilityProjection?)
    /// Use with CategoryType.RELIABILITY
    indirect case reliabilityProjection(ReliabilityProjection?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.v1.Impact"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
