// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// An insight along with the information used to derive the insight. The insight
/// may have associated recommendations as well.
public struct Insight: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of the insight.
  public var name: Swift.String = Swift.String()

  /// Free-form human readable summary in English. The maximum length is 500
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Fully qualified resource names that this insight is targeting.
  public var targetResources: [Swift.String] = []

  /// Insight subtype. Insight content schema will be stable for a given subtype.
  public var insightSubtype: Swift.String = Swift.String()

  /// A struct of custom fields to explain the insight.
  /// Example: "grantedPermissionsCount": "1000"
  public var content: GoogleWKT.Struct? = nil

  /// Timestamp of the latest data used to generate the insight.
  public var lastRefreshTime: GoogleWKT.Timestamp? = nil

  /// Observation period that led to the insight. The source data used to
  /// generate the insight ends at last_refresh_time and begins at
  /// (last_refresh_time - observation_period).
  public var observationPeriod: GoogleWKT.Duration? = nil

  /// Information state and metadata.
  public var stateInfo: InsightStateInfo? = nil

  /// Category being targeted by the insight.
  public var category: Insight.Category = Insight.Category()

  /// Insight's severity.
  public var severity: Insight.Severity = Insight.Severity()

  /// Fingerprint of the Insight. Provides optimistic locking when updating
  /// states.
  public var etag: Swift.String = Swift.String()

  /// Recommendations derived from this insight.
  public var associatedRecommendations: [Insight.RecommendationReference] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Insight`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Insight().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let targetResources = CodingKeys(stringValue: "targetResources")
    static let insightSubtype = CodingKeys(stringValue: "insightSubtype")
    static let content = CodingKeys(stringValue: "content")
    static let lastRefreshTime = CodingKeys(stringValue: "lastRefreshTime")
    static let observationPeriod = CodingKeys(stringValue: "observationPeriod")
    static let stateInfo = CodingKeys(stringValue: "stateInfo")
    static let category = CodingKeys(stringValue: "category")
    static let severity = CodingKeys(stringValue: "severity")
    static let etag = CodingKeys(stringValue: "etag")
    static let associatedRecommendations = CodingKeys(stringValue: "associatedRecommendations")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "targetResources",
      "insightSubtype",
      "content",
      "lastRefreshTime",
      "observationPeriod",
      "stateInfo",
      "category",
      "severity",
      "etag",
      "associatedRecommendations",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .targetResources) {
      self.targetResources = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .insightSubtype) {
      self.insightSubtype = value
    }
    self.content = try container.decodeIfPresent(GoogleWKT.Struct.self, forKey: .content)
    self.lastRefreshTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .lastRefreshTime)
    self.observationPeriod = try container.decodeIfPresent(
      GoogleWKT.Duration.self, forKey: .observationPeriod)
    self.stateInfo = try container.decodeIfPresent(InsightStateInfo.self, forKey: .stateInfo)
    if let value = try container.decodeIfPresent(Insight.Category.self, forKey: .category) {
      self.category = value
    }
    if let value = try container.decodeIfPresent(Insight.Severity.self, forKey: .severity) {
      self.severity = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(
      [Insight.RecommendationReference].self, forKey: .associatedRecommendations)
    {
      self.associatedRecommendations = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.targetResources, forKey: .targetResources)
    try container.encode(self.insightSubtype, forKey: .insightSubtype)
    try container.encodeIfPresent(self.content, forKey: .content)
    try container.encodeIfPresent(self.lastRefreshTime, forKey: .lastRefreshTime)
    try container.encodeIfPresent(self.observationPeriod, forKey: .observationPeriod)
    try container.encodeIfPresent(self.stateInfo, forKey: .stateInfo)
    try container.encode(self.category, forKey: .category)
    try container.encode(self.severity, forKey: .severity)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.associatedRecommendations, forKey: .associatedRecommendations)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Reference to an associated recommendation.
  public struct RecommendationReference: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Recommendation resource name, e.g.
    /// projects/[PROJECT_NUMBER]/locations/[LOCATION]/recommenders/[RECOMMENDER_ID]/recommendations/[RECOMMENDATION_ID]
    public var recommendation: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RecommendationReference`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RecommendationReference().with { $0.recommendation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let recommendation = CodingKeys(stringValue: "recommendation")

      static let _knownKeys: Set<Swift.String> = [
        "recommendation"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .recommendation) {
        self.recommendation = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.recommendation, forKey: .recommendation)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recommender.v1.Insight.RecommendationReference"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Insight category.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Category: Codable, Equatable, Sendable {
    /// Unspecified category.
    case unspecified
    /// The insight is related to cost.
    case cost
    /// The insight is related to security.
    case security
    /// The insight is related to performance.
    case performance
    /// This insight is related to manageability.
    case manageability
    /// The insight is related to sustainability.
    case sustainability
    /// This insight is related to reliability.
    case reliability
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cost: return 1
      case .security: return 2
      case .performance: return 3
      case .manageability: return 4
      case .sustainability: return 5
      case .reliability: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CATEGORY_UNSPECIFIED"
      case .cost: return "COST"
      case .security: return "SECURITY"
      case .performance: return "PERFORMANCE"
      case .manageability: return "MANAGEABILITY"
      case .sustainability: return "SUSTAINABILITY"
      case .reliability: return "RELIABILITY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Category/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CATEGORY_UNSPECIFIED": self = .unspecified
      case "COST": self = .cost
      case "SECURITY": self = .security
      case "PERFORMANCE": self = .performance
      case "MANAGEABILITY": self = .manageability
      case "SUSTAINABILITY": self = .sustainability
      case "RELIABILITY": self = .reliability
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Category/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cost
      case 2: self = .security
      case 3: self = .performance
      case 4: self = .manageability
      case 5: self = .sustainability
      case 6: self = .reliability
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CATEGORY_UNSPECIFIED")
      case .cost: return try container.encode("COST")
      case .security: return try container.encode("SECURITY")
      case .performance: return try container.encode("PERFORMANCE")
      case .manageability: return try container.encode("MANAGEABILITY")
      case .sustainability: return try container.encode("SUSTAINABILITY")
      case .reliability: return try container.encode("RELIABILITY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Insight severity levels.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Severity: Codable, Equatable, Sendable {
    /// Insight has unspecified severity.
    case unspecified
    /// Insight has low severity.
    case low
    /// Insight has medium severity.
    case medium
    /// Insight has high severity.
    case high
    /// Insight has critical severity.
    case critical
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .low: return 1
      case .medium: return 2
      case .high: return 3
      case .critical: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SEVERITY_UNSPECIFIED"
      case .low: return "LOW"
      case .medium: return "MEDIUM"
      case .high: return "HIGH"
      case .critical: return "CRITICAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Severity/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SEVERITY_UNSPECIFIED": self = .unspecified
      case "LOW": self = .low
      case "MEDIUM": self = .medium
      case "HIGH": self = .high
      case "CRITICAL": self = .critical
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Severity/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .low
      case 2: self = .medium
      case 3: self = .high
      case 4: self = .critical
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SEVERITY_UNSPECIFIED")
      case .low: return try container.encode("LOW")
      case .medium: return try container.encode("MEDIUM")
      case .high: return try container.encode("HIGH")
      case .critical: return try container.encode("CRITICAL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.v1.Insight"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
