// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for an InsightType.
public struct InsightTypeConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of insight type config.
  /// Eg,
  /// projects/[PROJECT_NUMBER]/locations/[LOCATION]/insightTypes/[INSIGHT_TYPE_ID]/config
  public var name: Swift.String = Swift.String()

  /// InsightTypeGenerationConfig which configures the generation of
  /// insights for this insight type.
  public var insightTypeGenerationConfig: InsightTypeGenerationConfig? = nil

  /// Fingerprint of the InsightTypeConfig. Provides optimistic locking when
  /// updating.
  public var etag: Swift.String = Swift.String()

  /// Last time when the config was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Immutable. The revision ID of the config.
  /// A new revision is committed whenever the config is changed in any way.
  /// The format is an 8-character hexadecimal string.
  public var revisionId: Swift.String = Swift.String()

  /// Allows clients to store small amounts of arbitrary data. Annotations must
  /// follow the Kubernetes syntax.
  /// The total size of all keys and values combined is limited to 256k.
  /// Key can have 2 segments: prefix (optional) and name (required),
  /// separated by a slash (/).
  /// Prefix must be a DNS subdomain.
  /// Name must be 63 characters or less, begin and end with alphanumerics,
  /// with dashes (-), underscores (_), dots (.), and alphanumerics between.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// A user-settable field to provide a human-readable name to be used in user
  /// interfaces.
  public var displayName: Swift.String = Swift.String()

  /// Initialize a new instance of `InsightTypeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InsightTypeConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.v1.InsightTypeConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
