// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request for the `ListRecommendations` method.
public struct ListRecommendationsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The container resource on which to execute the request.
  /// Acceptable formats:
  ///
  /// * `projects/[PROJECT_NUMBER]/locations/[LOCATION]/recommenders/[RECOMMENDER_ID]`
  ///
  /// * `projects/[PROJECT_ID]/locations/[LOCATION]/recommenders/[RECOMMENDER_ID]`
  ///
  /// * `billingAccounts/[BILLING_ACCOUNT_ID]/locations/[LOCATION]/recommenders/[RECOMMENDER_ID]`
  ///
  /// * `folders/[FOLDER_ID]/locations/[LOCATION]/recommenders/[RECOMMENDER_ID]`
  ///
  /// * `organizations/[ORGANIZATION_ID]/locations/[LOCATION]/recommenders/[RECOMMENDER_ID]`
  ///
  /// LOCATION here refers to GCP Locations:
  /// https://cloud.google.com/about/locations/
  /// RECOMMENDER_ID refers to supported recommenders:
  /// https://cloud.google.com/recommender/docs/recommenders.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of results to return from this request.
  /// Non-positive values are ignored. If not specified, the server will
  /// determine the number of results to return.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. If present, retrieves the next batch of results from the
  /// preceding call to this method. `page_token` must be the value of
  /// `next_page_token` from the previous response. The values of other method
  /// parameters must be identical to those in the previous call.
  public var pageToken: Swift.String = Swift.String()

  /// Filter expression to restrict the recommendations returned. Supported
  /// filter fields:
  ///
  /// * `state_info.state`
  ///
  /// * `recommenderSubtype`
  ///
  /// * `priority`
  ///
  /// * `targetResources`
  ///
  /// Examples:
  ///
  /// * `stateInfo.state = ACTIVE OR stateInfo.state = DISMISSED`
  ///
  /// * `recommenderSubtype = REMOVE_ROLE OR recommenderSubtype = REPLACE_ROLE`
  ///
  /// * `priority = P1 OR priority = P2`
  ///
  /// * `targetResources :
  /// //compute.googleapis.com/projects/1234/zones/us-central1-a/instances/instance-1`
  ///
  /// * `stateInfo.state = ACTIVE AND (priority = P1 OR priority = P2)`
  ///
  /// The max allowed filter length is 500 characters.
  ///
  /// (These expressions are based on the filter language described at
  /// https://google.aip.dev/160)
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListRecommendationsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListRecommendationsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.v1.ListRecommendationsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
