// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the `MarkRecommendationFailed` Method.
public struct MarkRecommendationFailedRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the recommendation.
  public var name: Swift.String = Swift.String()

  /// State properties to include with this state. Overwrites any existing
  /// `state_metadata`.
  /// Keys must match the regex `/^[a-z0-9][a-z0-9_.-]{0,62}$/`.
  /// Values must match the regex `/^[a-zA-Z0-9_./-]{0,255}$/`.
  public var stateMetadata: [Swift.String: Swift.String] = [:]

  /// Required. Fingerprint of the Recommendation. Provides optimistic locking.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `MarkRecommendationFailedRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MarkRecommendationFailedRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.v1.MarkRecommendationFailedRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
