// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A recommendation along with a suggested action. E.g., a rightsizing
/// recommendation for an underutilized VM, IAM role recommendations, etc
public struct Recommendation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of recommendation.
  public var name: Swift.String = Swift.String()

  /// Free-form human readable summary in English. The maximum length is 500
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Contains an identifier for a subtype of recommendations produced for the
  /// same recommender. Subtype is a function of content and impact, meaning a
  /// new subtype might be added when significant changes to `content` or
  /// `primary_impact.category` are introduced. See the Recommenders section
  /// to see a list of subtypes for a given Recommender.
  ///
  /// Examples:
  ///   For recommender = "google.iam.policy.Recommender",
  ///   recommender_subtype can be one of "REMOVE_ROLE"/"REPLACE_ROLE"
  public var recommenderSubtype: Swift.String = Swift.String()

  /// Last time this recommendation was refreshed by the system that created it
  /// in the first place.
  public var lastRefreshTime: GoogleCloudWKT.Timestamp? = nil

  /// The primary impact that this recommendation can have while trying to
  /// optimize for one category.
  public var primaryImpact: Impact? = nil

  /// Optional set of additional impact that this recommendation may have when
  /// trying to optimize for the primary category. These may be positive
  /// or negative.
  public var additionalImpact: [Impact] = []

  /// Recommendation's priority.
  public var priority: Recommendation.Priority = Recommendation.Priority()

  /// Content of the recommendation describing recommended changes to resources.
  public var content: RecommendationContent? = nil

  /// Information for state. Contains state and metadata.
  public var stateInfo: RecommendationStateInfo? = nil

  /// Fingerprint of the Recommendation. Provides optimistic locking when
  /// updating states.
  public var etag: Swift.String = Swift.String()

  /// Insights that led to this recommendation.
  public var associatedInsights: [Recommendation.InsightReference] = []

  /// Corresponds to a mutually exclusive group ID within a recommender.
  /// A non-empty ID indicates that the recommendation belongs to a mutually
  /// exclusive group. This means that only one recommendation within the group
  /// is suggested to be applied.
  public var xorGroupId: Swift.String = Swift.String()

  /// Fully qualified resource names that this recommendation is targeting.
  public var targetResources: [Swift.String] = []

  /// Initialize a new instance of `Recommendation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Recommendation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Reference to an associated insight.
  public struct InsightReference: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Insight resource name, e.g.
    /// projects/[PROJECT_NUMBER]/locations/[LOCATION]/insightTypes/[INSIGHT_TYPE_ID]/insights/[INSIGHT_ID]
    public var insight: Swift.String = Swift.String()

    /// Initialize a new instance of `InsightReference`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InsightReference().with { $0.insight = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.recommender.v1.Recommendation.InsightReference"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Recommendation priority levels.
  public enum Priority: Codable, Equatable, Sendable {
    /// Recommendation has unspecified priority.
    case unspecified
    /// Recommendation has P4 priority (lowest priority).
    case p4
    /// Recommendation has P3 priority (second lowest priority).
    case p3
    /// Recommendation has P2 priority (second highest priority).
    case p2
    /// Recommendation has P1 priority (highest priority).
    case p1
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .p4: return 1
      case .p3: return 2
      case .p2: return 3
      case .p1: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PRIORITY_UNSPECIFIED"
      case .p4: return "P4"
      case .p3: return "P3"
      case .p2: return "P2"
      case .p1: return "P1"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Priority/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PRIORITY_UNSPECIFIED": self = .unspecified
      case "P4": self = .p4
      case "P3": self = .p3
      case "P2": self = .p2
      case "P1": self = .p1
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Priority/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .p4
      case 2: self = .p3
      case 3: self = .p2
      case 4: self = .p1
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .p4: return try container.encode(1)
      case .p3: return try container.encode(2)
      case .p2: return try container.encode(3)
      case .p1: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.v1.Recommendation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
