// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class RecommenderLogging: RecommenderStub {
    let inner: any RecommenderStub
    let logger: Logger

    public init(_ inner: any RecommenderStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-recommender-v1"
      logger[metadataKey: "gcp.client.service"] = "recommender"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Recommender"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listInsights(
      request: ListInsightsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.ListInsightsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listInsights",
        action: {
          (r: ListInsightsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.ListInsightsResponse
          in
          return try await self.inner.listInsights(request: r, options: o)
        })
    }

    public func getInsight(
      request: GetInsightRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Insight {
      try await self._intercept(
        request: request,
        options: options,
        name: "getInsight",
        action: {
          (r: GetInsightRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Insight
          in
          return try await self.inner.getInsight(request: r, options: o)
        })
    }

    public func markInsightAccepted(
      request: MarkInsightAcceptedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Insight {
      try await self._intercept(
        request: request,
        options: options,
        name: "markInsightAccepted",
        action: {
          (r: MarkInsightAcceptedRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Insight
          in
          return try await self.inner.markInsightAccepted(request: r, options: o)
        })
    }

    public func listRecommendations(
      request: ListRecommendationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.ListRecommendationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listRecommendations",
        action: {
          (r: ListRecommendationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.ListRecommendationsResponse
          in
          return try await self.inner.listRecommendations(request: r, options: o)
        })
    }

    public func getRecommendation(
      request: GetRecommendationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRecommendation",
        action: {
          (r: GetRecommendationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Recommendation
          in
          return try await self.inner.getRecommendation(request: r, options: o)
        })
    }

    public func markRecommendationDismissed(
      request: MarkRecommendationDismissedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      try await self._intercept(
        request: request,
        options: options,
        name: "markRecommendationDismissed",
        action: {
          (r: MarkRecommendationDismissedRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Recommendation
          in
          return try await self.inner.markRecommendationDismissed(request: r, options: o)
        })
    }

    public func markRecommendationClaimed(
      request: MarkRecommendationClaimedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      try await self._intercept(
        request: request,
        options: options,
        name: "markRecommendationClaimed",
        action: {
          (r: MarkRecommendationClaimedRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Recommendation
          in
          return try await self.inner.markRecommendationClaimed(request: r, options: o)
        })
    }

    public func markRecommendationSucceeded(
      request: MarkRecommendationSucceededRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      try await self._intercept(
        request: request,
        options: options,
        name: "markRecommendationSucceeded",
        action: {
          (r: MarkRecommendationSucceededRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Recommendation
          in
          return try await self.inner.markRecommendationSucceeded(request: r, options: o)
        })
    }

    public func markRecommendationFailed(
      request: MarkRecommendationFailedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      try await self._intercept(
        request: request,
        options: options,
        name: "markRecommendationFailed",
        action: {
          (r: MarkRecommendationFailedRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Recommendation
          in
          return try await self.inner.markRecommendationFailed(request: r, options: o)
        })
    }

    public func getRecommenderConfig(
      request: GetRecommenderConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getRecommenderConfig",
        action: {
          (r: GetRecommenderConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.RecommenderConfig
          in
          return try await self.inner.getRecommenderConfig(request: r, options: o)
        })
    }

    public func updateRecommenderConfig(
      request: UpdateRecommenderConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateRecommenderConfig",
        action: {
          (r: UpdateRecommenderConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.RecommenderConfig
          in
          return try await self.inner.updateRecommenderConfig(request: r, options: o)
        })
    }

    public func getInsightTypeConfig(
      request: GetInsightTypeConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getInsightTypeConfig",
        action: {
          (r: GetInsightTypeConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.InsightTypeConfig
          in
          return try await self.inner.getInsightTypeConfig(request: r, options: o)
        })
    }

    public func updateInsightTypeConfig(
      request: UpdateInsightTypeConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateInsightTypeConfig",
        action: {
          (r: UpdateInsightTypeConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.InsightTypeConfig
          in
          return try await self.inner.updateInsightTypeConfig(request: r, options: o)
        })
    }
  }
}
