// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax

/// Provides insights and recommendations for cloud customers for various
/// categories like performance optimization, cost savings, reliability, feature
/// discovery, etc. Insights and recommendations are generated automatically
/// based on analysis of user resources, configuration and monitoring metrics.
///
/// @Snippet(path: "RecommenderQuickstart")
public final class RecommenderClient: Clients.RecommenderProtocol, Sendable {
  let inner: any Clients.RecommenderStub

  /// Creates a new `RecommenderClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.RecommenderStub = try Clients.RecommenderTransport(options)
    inner = Clients.RecommenderRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.RecommenderLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists insights for the specified Cloud Resource. Requires the
  /// recommender.*.list IAM permission for the specified insight type.
  ///
  /// @Snippet(path: "Recommender_ListInsights")
  public func listInsights(
    request: ListInsightsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.ListInsightsResponse {
    try await self.inner.listInsights(request: request, options: options)
  }

  /// Lists insights for the specified Cloud Resource. Requires the
  /// recommender.*.list IAM permission for the specified insight type.
  ///
  /// @Snippet(path: "Recommender_ListInsights")
  public func listInsights(
    byItem: ListInsightsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Insight, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRecommenderV1.ListInsightsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listInsights(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the requested insight. Requires the recommender.*.get IAM permission
  /// for the specified insight type.
  ///
  /// @Snippet(path: "Recommender_GetInsight")
  public func getInsight(
    request: GetInsightRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Insight {
    try await self.inner.getInsight(request: request, options: options)
  }

  /// Marks the Insight State as Accepted. Users can use this method to
  /// indicate to the Recommender API that they have applied some action based
  /// on the insight. This stops the insight content from being updated.
  ///
  /// MarkInsightAccepted can be applied to insights in ACTIVE state. Requires
  /// the recommender.*.update IAM permission for the specified insight.
  ///
  /// @Snippet(path: "Recommender_MarkInsightAccepted")
  public func markInsightAccepted(
    request: MarkInsightAcceptedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Insight {
    try await self.inner.markInsightAccepted(request: request, options: options)
  }

  /// Lists recommendations for the specified Cloud Resource. Requires the
  /// recommender.*.list IAM permission for the specified recommender.
  ///
  /// @Snippet(path: "Recommender_ListRecommendations")
  public func listRecommendations(
    request: ListRecommendationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.ListRecommendationsResponse {
    try await self.inner.listRecommendations(request: request, options: options)
  }

  /// Lists recommendations for the specified Cloud Resource. Requires the
  /// recommender.*.list IAM permission for the specified recommender.
  ///
  /// @Snippet(path: "Recommender_ListRecommendations")
  public func listRecommendations(
    byItem: ListRecommendationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Recommendation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRecommenderV1.ListRecommendationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listRecommendations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the requested recommendation. Requires the recommender.*.get
  /// IAM permission for the specified recommender.
  ///
  /// @Snippet(path: "Recommender_GetRecommendation")
  public func getRecommendation(
    request: GetRecommendationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    try await self.inner.getRecommendation(request: request, options: options)
  }

  /// Mark the Recommendation State as Dismissed. Users can use this method to
  /// indicate to the Recommender API that an ACTIVE recommendation has to
  /// be marked back as DISMISSED.
  ///
  /// MarkRecommendationDismissed can be applied to recommendations in ACTIVE
  /// state.
  ///
  /// Requires the recommender.*.update IAM permission for the specified
  /// recommender.
  ///
  /// @Snippet(path: "Recommender_MarkRecommendationDismissed")
  public func markRecommendationDismissed(
    request: MarkRecommendationDismissedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    try await self.inner.markRecommendationDismissed(request: request, options: options)
  }

  /// Marks the Recommendation State as Claimed. Users can use this method to
  /// indicate to the Recommender API that they are starting to apply the
  /// recommendation themselves. This stops the recommendation content from being
  /// updated. Associated insights are frozen and placed in the ACCEPTED state.
  ///
  /// MarkRecommendationClaimed can be applied to recommendations in CLAIMED,
  /// SUCCEEDED, FAILED, or ACTIVE state.
  ///
  /// Requires the recommender.*.update IAM permission for the specified
  /// recommender.
  ///
  /// @Snippet(path: "Recommender_MarkRecommendationClaimed")
  public func markRecommendationClaimed(
    request: MarkRecommendationClaimedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    try await self.inner.markRecommendationClaimed(request: request, options: options)
  }

  /// Marks the Recommendation State as Succeeded. Users can use this method to
  /// indicate to the Recommender API that they have applied the recommendation
  /// themselves, and the operation was successful. This stops the recommendation
  /// content from being updated. Associated insights are frozen and placed in
  /// the ACCEPTED state.
  ///
  /// MarkRecommendationSucceeded can be applied to recommendations in ACTIVE,
  /// CLAIMED, SUCCEEDED, or FAILED state.
  ///
  /// Requires the recommender.*.update IAM permission for the specified
  /// recommender.
  ///
  /// @Snippet(path: "Recommender_MarkRecommendationSucceeded")
  public func markRecommendationSucceeded(
    request: MarkRecommendationSucceededRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    try await self.inner.markRecommendationSucceeded(request: request, options: options)
  }

  /// Marks the Recommendation State as Failed. Users can use this method to
  /// indicate to the Recommender API that they have applied the recommendation
  /// themselves, and the operation failed. This stops the recommendation content
  /// from being updated. Associated insights are frozen and placed in the
  /// ACCEPTED state.
  ///
  /// MarkRecommendationFailed can be applied to recommendations in ACTIVE,
  /// CLAIMED, SUCCEEDED, or FAILED state.
  ///
  /// Requires the recommender.*.update IAM permission for the specified
  /// recommender.
  ///
  /// @Snippet(path: "Recommender_MarkRecommendationFailed")
  public func markRecommendationFailed(
    request: MarkRecommendationFailedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    try await self.inner.markRecommendationFailed(request: request, options: options)
  }

  /// Gets the requested Recommender Config. There is only one instance of the
  /// config for each Recommender.
  ///
  /// @Snippet(path: "Recommender_GetRecommenderConfig")
  public func getRecommenderConfig(
    request: GetRecommenderConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
    try await self.inner.getRecommenderConfig(request: request, options: options)
  }

  /// Updates a Recommender Config. This will create a new revision of the
  /// config.
  ///
  /// @Snippet(path: "Recommender_UpdateRecommenderConfig")
  public func updateRecommenderConfig(
    request: UpdateRecommenderConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
    try await self.inner.updateRecommenderConfig(request: request, options: options)
  }

  /// Gets the requested InsightTypeConfig. There is only one instance of the
  /// config for each InsightType.
  ///
  /// @Snippet(path: "Recommender_GetInsightTypeConfig")
  public func getInsightTypeConfig(
    request: GetInsightTypeConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
    try await self.inner.getInsightTypeConfig(request: request, options: options)
  }

  /// Updates an InsightTypeConfig change. This will create a new revision of the
  /// config.
  ///
  /// @Snippet(path: "Recommender_UpdateInsightTypeConfig")
  public func updateInsightTypeConfig(
    request: UpdateInsightTypeConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
    try await self.inner.updateInsightTypeConfig(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `RecommenderClient`.
  ///
  /// To mock `RecommenderClient` change your functions to receive
  /// `some RecommenderProtocol` or `any RecommenderProtocol`
  /// and pass a mock implementation in your tests.
  public protocol RecommenderProtocol {
    /// See `RecommenderClient.listInsights`.
    func listInsights(request: ListInsightsRequest) async throws
      -> GoogleCloudRecommenderV1.ListInsightsResponse

    /// See `RecommenderClient.listInsights`.
    func listInsights(
      byItem: ListInsightsRequest
    ) throws -> any AsyncSequence<Insight, Swift.Error>

    /// See `RecommenderClient.listInsights`.
    func listInsights(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Insight, Swift.Error>

    /// See `RecommenderClient.getInsight`.
    func getInsight(request: GetInsightRequest) async throws -> GoogleCloudRecommenderV1.Insight

    /// See `RecommenderClient.getInsight`.
    func getInsight(
      name: Swift.String,
    ) async throws -> GoogleCloudRecommenderV1.Insight

    /// See `RecommenderClient.markInsightAccepted`.
    func markInsightAccepted(request: MarkInsightAcceptedRequest) async throws
      -> GoogleCloudRecommenderV1.Insight

    /// See `RecommenderClient.markInsightAccepted`.
    func markInsightAccepted(
      name: Swift.String,
      stateMetadata: [Swift.String: Swift.String],
      etag: Swift.String,
    ) async throws -> GoogleCloudRecommenderV1.Insight

    /// See `RecommenderClient.listRecommendations`.
    func listRecommendations(request: ListRecommendationsRequest) async throws
      -> GoogleCloudRecommenderV1.ListRecommendationsResponse

    /// See `RecommenderClient.listRecommendations`.
    func listRecommendations(
      byItem: ListRecommendationsRequest
    ) throws -> any AsyncSequence<Recommendation, Swift.Error>

    /// See `RecommenderClient.listRecommendations`.
    func listRecommendations(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Recommendation, Swift.Error>

    /// See `RecommenderClient.listRecommendations`.
    func listRecommendations(
      parent: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<Recommendation, Swift.Error>

    /// See `RecommenderClient.getRecommendation`.
    func getRecommendation(request: GetRecommendationRequest) async throws
      -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.getRecommendation`.
    func getRecommendation(
      name: Swift.String,
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.markRecommendationDismissed`.
    func markRecommendationDismissed(request: MarkRecommendationDismissedRequest) async throws
      -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.markRecommendationClaimed`.
    func markRecommendationClaimed(request: MarkRecommendationClaimedRequest) async throws
      -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.markRecommendationClaimed`.
    func markRecommendationClaimed(
      name: Swift.String,
      stateMetadata: [Swift.String: Swift.String],
      etag: Swift.String,
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.markRecommendationSucceeded`.
    func markRecommendationSucceeded(request: MarkRecommendationSucceededRequest) async throws
      -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.markRecommendationSucceeded`.
    func markRecommendationSucceeded(
      name: Swift.String,
      stateMetadata: [Swift.String: Swift.String],
      etag: Swift.String,
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.markRecommendationFailed`.
    func markRecommendationFailed(request: MarkRecommendationFailedRequest) async throws
      -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.markRecommendationFailed`.
    func markRecommendationFailed(
      name: Swift.String,
      stateMetadata: [Swift.String: Swift.String],
      etag: Swift.String,
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.getRecommenderConfig`.
    func getRecommenderConfig(request: GetRecommenderConfigRequest) async throws
      -> GoogleCloudRecommenderV1.RecommenderConfig

    /// See `RecommenderClient.getRecommenderConfig`.
    func getRecommenderConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig

    /// See `RecommenderClient.updateRecommenderConfig`.
    func updateRecommenderConfig(request: UpdateRecommenderConfigRequest) async throws
      -> GoogleCloudRecommenderV1.RecommenderConfig

    /// See `RecommenderClient.updateRecommenderConfig`.
    func updateRecommenderConfig(
      recommenderConfig: RecommenderConfig?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig

    /// See `RecommenderClient.getInsightTypeConfig`.
    func getInsightTypeConfig(request: GetInsightTypeConfigRequest) async throws
      -> GoogleCloudRecommenderV1.InsightTypeConfig

    /// See `RecommenderClient.getInsightTypeConfig`.
    func getInsightTypeConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig

    /// See `RecommenderClient.updateInsightTypeConfig`.
    func updateInsightTypeConfig(request: UpdateInsightTypeConfigRequest) async throws
      -> GoogleCloudRecommenderV1.InsightTypeConfig

    /// See `RecommenderClient.updateInsightTypeConfig`.
    func updateInsightTypeConfig(
      insightTypeConfig: InsightTypeConfig?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig

    /// See `RecommenderClient.listInsights`.
    func listInsights(
      request: ListInsightsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.ListInsightsResponse

    /// See `RecommenderClient.listInsights`.
    func listInsights(
      byItem: ListInsightsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Insight, Swift.Error>

    /// See `RecommenderClient.getInsight`.
    func getInsight(
      request: GetInsightRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Insight

    /// See `RecommenderClient.markInsightAccepted`.
    func markInsightAccepted(
      request: MarkInsightAcceptedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Insight

    /// See `RecommenderClient.listRecommendations`.
    func listRecommendations(
      request: ListRecommendationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.ListRecommendationsResponse

    /// See `RecommenderClient.listRecommendations`.
    func listRecommendations(
      byItem: ListRecommendationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Recommendation, Swift.Error>

    /// See `RecommenderClient.getRecommendation`.
    func getRecommendation(
      request: GetRecommendationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.markRecommendationDismissed`.
    func markRecommendationDismissed(
      request: MarkRecommendationDismissedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.markRecommendationClaimed`.
    func markRecommendationClaimed(
      request: MarkRecommendationClaimedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.markRecommendationSucceeded`.
    func markRecommendationSucceeded(
      request: MarkRecommendationSucceededRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.markRecommendationFailed`.
    func markRecommendationFailed(
      request: MarkRecommendationFailedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    /// See `RecommenderClient.getRecommenderConfig`.
    func getRecommenderConfig(
      request: GetRecommenderConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig

    /// See `RecommenderClient.updateRecommenderConfig`.
    func updateRecommenderConfig(
      request: UpdateRecommenderConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig

    /// See `RecommenderClient.getInsightTypeConfig`.
    func getInsightTypeConfig(
      request: GetInsightTypeConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig

    /// See `RecommenderClient.updateInsightTypeConfig`.
    func updateInsightTypeConfig(
      request: UpdateInsightTypeConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig
  }
}

// Default implementations
extension Clients.RecommenderProtocol {
  public func listInsights(request: ListInsightsRequest) async throws
    -> GoogleCloudRecommenderV1.ListInsightsResponse
  {
    try await self.listInsights(request: request, options: .init())
  }

  public func listInsights(
    request: ListInsightsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.ListInsightsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listInsights(
    byItem: ListInsightsRequest
  ) throws -> any AsyncSequence<Insight, Swift.Error> {
    try self.listInsights(byItem: byItem, options: .init())
  }

  public func listInsights(
    byItem: ListInsightsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Insight, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRecommenderV1.ListInsightsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInsights(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Insight, Swift.Error> {
    let request = ListInsightsRequest().with {
      $0.parent = parent
    }
    return try self.listInsights(byItem: request)
  }

  public func getInsight(request: GetInsightRequest) async throws
    -> GoogleCloudRecommenderV1.Insight
  {
    try await self.getInsight(request: request, options: .init())
  }

  public func getInsight(
    request: GetInsightRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Insight {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getInsight(
    name: Swift.String,
  ) async throws -> GoogleCloudRecommenderV1.Insight {
    let request = GetInsightRequest().with {
      $0.name = name
    }
    return try await self.getInsight(request: request)
  }

  public func markInsightAccepted(request: MarkInsightAcceptedRequest) async throws
    -> GoogleCloudRecommenderV1.Insight
  {
    try await self.markInsightAccepted(request: request, options: .init())
  }

  public func markInsightAccepted(
    request: MarkInsightAcceptedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Insight {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func markInsightAccepted(
    name: Swift.String,
    stateMetadata: [Swift.String: Swift.String],
    etag: Swift.String,
  ) async throws -> GoogleCloudRecommenderV1.Insight {
    let request = MarkInsightAcceptedRequest().with {
      $0.name = name
      $0.stateMetadata = stateMetadata
      $0.etag = etag
    }
    return try await self.markInsightAccepted(request: request)
  }

  public func listRecommendations(request: ListRecommendationsRequest) async throws
    -> GoogleCloudRecommenderV1.ListRecommendationsResponse
  {
    try await self.listRecommendations(request: request, options: .init())
  }

  public func listRecommendations(
    request: ListRecommendationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.ListRecommendationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listRecommendations(
    byItem: ListRecommendationsRequest
  ) throws -> any AsyncSequence<Recommendation, Swift.Error> {
    try self.listRecommendations(byItem: byItem, options: .init())
  }

  public func listRecommendations(
    byItem: ListRecommendationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Recommendation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRecommenderV1.ListRecommendationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRecommendations(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Recommendation, Swift.Error> {
    let request = ListRecommendationsRequest().with {
      $0.parent = parent
    }
    return try self.listRecommendations(byItem: request)
  }

  public func listRecommendations(
    parent: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<Recommendation, Swift.Error> {
    let request = ListRecommendationsRequest().with {
      $0.parent = parent
      $0.filter = filter
    }
    return try self.listRecommendations(byItem: request)
  }

  public func getRecommendation(request: GetRecommendationRequest) async throws
    -> GoogleCloudRecommenderV1.Recommendation
  {
    try await self.getRecommendation(request: request, options: .init())
  }

  public func getRecommendation(
    request: GetRecommendationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getRecommendation(
    name: Swift.String,
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    let request = GetRecommendationRequest().with {
      $0.name = name
    }
    return try await self.getRecommendation(request: request)
  }

  public func markRecommendationDismissed(request: MarkRecommendationDismissedRequest) async throws
    -> GoogleCloudRecommenderV1.Recommendation
  {
    try await self.markRecommendationDismissed(request: request, options: .init())
  }

  public func markRecommendationDismissed(
    request: MarkRecommendationDismissedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func markRecommendationClaimed(request: MarkRecommendationClaimedRequest) async throws
    -> GoogleCloudRecommenderV1.Recommendation
  {
    try await self.markRecommendationClaimed(request: request, options: .init())
  }

  public func markRecommendationClaimed(
    request: MarkRecommendationClaimedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func markRecommendationClaimed(
    name: Swift.String,
    stateMetadata: [Swift.String: Swift.String],
    etag: Swift.String,
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    let request = MarkRecommendationClaimedRequest().with {
      $0.name = name
      $0.stateMetadata = stateMetadata
      $0.etag = etag
    }
    return try await self.markRecommendationClaimed(request: request)
  }

  public func markRecommendationSucceeded(request: MarkRecommendationSucceededRequest) async throws
    -> GoogleCloudRecommenderV1.Recommendation
  {
    try await self.markRecommendationSucceeded(request: request, options: .init())
  }

  public func markRecommendationSucceeded(
    request: MarkRecommendationSucceededRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func markRecommendationSucceeded(
    name: Swift.String,
    stateMetadata: [Swift.String: Swift.String],
    etag: Swift.String,
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    let request = MarkRecommendationSucceededRequest().with {
      $0.name = name
      $0.stateMetadata = stateMetadata
      $0.etag = etag
    }
    return try await self.markRecommendationSucceeded(request: request)
  }

  public func markRecommendationFailed(request: MarkRecommendationFailedRequest) async throws
    -> GoogleCloudRecommenderV1.Recommendation
  {
    try await self.markRecommendationFailed(request: request, options: .init())
  }

  public func markRecommendationFailed(
    request: MarkRecommendationFailedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func markRecommendationFailed(
    name: Swift.String,
    stateMetadata: [Swift.String: Swift.String],
    etag: Swift.String,
  ) async throws -> GoogleCloudRecommenderV1.Recommendation {
    let request = MarkRecommendationFailedRequest().with {
      $0.name = name
      $0.stateMetadata = stateMetadata
      $0.etag = etag
    }
    return try await self.markRecommendationFailed(request: request)
  }

  public func getRecommenderConfig(request: GetRecommenderConfigRequest) async throws
    -> GoogleCloudRecommenderV1.RecommenderConfig
  {
    try await self.getRecommenderConfig(request: request, options: .init())
  }

  public func getRecommenderConfig(
    request: GetRecommenderConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getRecommenderConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
    let request = GetRecommenderConfigRequest().with {
      $0.name = name
    }
    return try await self.getRecommenderConfig(request: request)
  }

  public func updateRecommenderConfig(request: UpdateRecommenderConfigRequest) async throws
    -> GoogleCloudRecommenderV1.RecommenderConfig
  {
    try await self.updateRecommenderConfig(request: request, options: .init())
  }

  public func updateRecommenderConfig(
    request: UpdateRecommenderConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateRecommenderConfig(
    recommenderConfig: RecommenderConfig?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
    let request = UpdateRecommenderConfigRequest().with {
      $0.recommenderConfig = recommenderConfig
      $0.updateMask = updateMask
    }
    return try await self.updateRecommenderConfig(request: request)
  }

  public func getInsightTypeConfig(request: GetInsightTypeConfigRequest) async throws
    -> GoogleCloudRecommenderV1.InsightTypeConfig
  {
    try await self.getInsightTypeConfig(request: request, options: .init())
  }

  public func getInsightTypeConfig(
    request: GetInsightTypeConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getInsightTypeConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
    let request = GetInsightTypeConfigRequest().with {
      $0.name = name
    }
    return try await self.getInsightTypeConfig(request: request)
  }

  public func updateInsightTypeConfig(request: UpdateInsightTypeConfigRequest) async throws
    -> GoogleCloudRecommenderV1.InsightTypeConfig
  {
    try await self.updateInsightTypeConfig(request: request, options: .init())
  }

  public func updateInsightTypeConfig(
    request: UpdateInsightTypeConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateInsightTypeConfig(
    insightTypeConfig: InsightTypeConfig?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
    let request = UpdateInsightTypeConfigRequest().with {
      $0.insightTypeConfig = insightTypeConfig
      $0.updateMask = updateMask
    }
    return try await self.updateInsightTypeConfig(request: request)
  }
}
