// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class RecommenderRetry: RecommenderStub {
    let inner: any RecommenderStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any RecommenderStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listInsights(
      request: ListInsightsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.ListInsightsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListInsightsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.ListInsightsResponse
          in
          return try await self.inner.listInsights(request: r, options: o)
        })
    }

    public func getInsight(
      request: GetInsightRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Insight {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetInsightRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Insight
          in
          return try await self.inner.getInsight(request: r, options: o)
        })
    }

    public func markInsightAccepted(
      request: MarkInsightAcceptedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Insight {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: MarkInsightAcceptedRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Insight
          in
          return try await self.inner.markInsightAccepted(request: r, options: o)
        })
    }

    public func listRecommendations(
      request: ListRecommendationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.ListRecommendationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListRecommendationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.ListRecommendationsResponse
          in
          return try await self.inner.listRecommendations(request: r, options: o)
        })
    }

    public func getRecommendation(
      request: GetRecommendationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetRecommendationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Recommendation
          in
          return try await self.inner.getRecommendation(request: r, options: o)
        })
    }

    public func markRecommendationDismissed(
      request: MarkRecommendationDismissedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: MarkRecommendationDismissedRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Recommendation
          in
          return try await self.inner.markRecommendationDismissed(request: r, options: o)
        })
    }

    public func markRecommendationClaimed(
      request: MarkRecommendationClaimedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: MarkRecommendationClaimedRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Recommendation
          in
          return try await self.inner.markRecommendationClaimed(request: r, options: o)
        })
    }

    public func markRecommendationSucceeded(
      request: MarkRecommendationSucceededRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: MarkRecommendationSucceededRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Recommendation
          in
          return try await self.inner.markRecommendationSucceeded(request: r, options: o)
        })
    }

    public func markRecommendationFailed(
      request: MarkRecommendationFailedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: MarkRecommendationFailedRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.Recommendation
          in
          return try await self.inner.markRecommendationFailed(request: r, options: o)
        })
    }

    public func getRecommenderConfig(
      request: GetRecommenderConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetRecommenderConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.RecommenderConfig
          in
          return try await self.inner.getRecommenderConfig(request: r, options: o)
        })
    }

    public func updateRecommenderConfig(
      request: UpdateRecommenderConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateRecommenderConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.RecommenderConfig
          in
          return try await self.inner.updateRecommenderConfig(request: r, options: o)
        })
    }

    public func getInsightTypeConfig(
      request: GetInsightTypeConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetInsightTypeConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.InsightTypeConfig
          in
          return try await self.inner.getInsightTypeConfig(request: r, options: o)
        })
    }

    public func updateInsightTypeConfig(
      request: UpdateInsightTypeConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateInsightTypeConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudRecommenderV1.InsightTypeConfig
          in
          return try await self.inner.updateInsightTypeConfig(request: r, options: o)
        })
    }
  }
}
