// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleWKT
import GoogleGax

extension Clients {
  protocol RecommenderStub: Sendable {
    func listInsights(
      request: ListInsightsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.ListInsightsResponse

    func getInsight(
      request: GetInsightRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Insight

    func markInsightAccepted(
      request: MarkInsightAcceptedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Insight

    func listRecommendations(
      request: ListRecommendationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.ListRecommendationsResponse

    func getRecommendation(
      request: GetRecommendationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    func markRecommendationDismissed(
      request: MarkRecommendationDismissedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    func markRecommendationClaimed(
      request: MarkRecommendationClaimedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    func markRecommendationSucceeded(
      request: MarkRecommendationSucceededRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    func markRecommendationFailed(
      request: MarkRecommendationFailedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation

    func getRecommenderConfig(
      request: GetRecommenderConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig

    func updateRecommenderConfig(
      request: UpdateRecommenderConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig

    func getInsightTypeConfig(
      request: GetInsightTypeConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig

    func updateInsightTypeConfig(
      request: UpdateInsightTypeConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig
  }
}
