// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Information for state. Contains state and metadata.
public struct RecommendationStateInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The state of the recommendation, Eg ACTIVE, SUCCEEDED, FAILED.
  public var state: RecommendationStateInfo.State = RecommendationStateInfo.State()

  /// A map of metadata for the state, provided by user or automations systems.
  public var stateMetadata: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `RecommendationStateInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RecommendationStateInfo().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Represents Recommendation State.
  public enum State: Codable, Equatable, Sendable {
    /// Default state. Don't use directly.
    case unspecified
    /// Recommendation is active and can be applied. Recommendations content can
    /// be updated by Google.
    ///
    /// ACTIVE recommendations can be marked as CLAIMED, SUCCEEDED, or FAILED.
    case active
    /// Recommendation is in succeeded state. Recommendations content is
    /// immutable and cannot be updated by Google.
    ///
    /// SUCCEEDED recommendations can be marked as SUCCEEDED, or FAILED.
    case succeeded
    /// Recommendation is in failed state. Recommendations content is immutable
    /// and cannot be updated by Google.
    ///
    /// FAILED recommendations can be marked as SUCCEEDED, or FAILED.
    case failed
    /// Recommendation is in dismissed state. Recommendation content can be
    /// updated by Google.
    ///
    /// DISMISSED recommendations can be marked as ACTIVE.
    case dismissed
    /// Recommendation is in claimed state. Recommendations content is
    /// immutable and cannot be updated by Google.
    ///
    /// CLAIMED recommendations can be marked as CLAIMED, SUCCEEDED, or FAILED.
    case claimed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .succeeded: return 3
      case .failed: return 4
      case .dismissed: return 5
      case .claimed: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .dismissed: return "DISMISSED"
      case .claimed: return "CLAIMED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "CLAIMED": self = .claimed
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "DISMISSED": self = .dismissed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 3: self = .succeeded
      case 4: self = .failed
      case 5: self = .dismissed
      case 6: self = .claimed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .succeeded: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .dismissed: return try container.encode(5)
      case .claimed: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.v1.RecommendationStateInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
