// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class RecommenderTransport: RecommenderStub {
    let inner: GoogleGax._HTTPClient

    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      self.inner = try GoogleGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://recommender.googleapis.com",
      )
    }

    @concurrent
    public func listInsights(
      request: ListInsightsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.ListInsightsResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/insightTypes/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/insights"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/insightTypes/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/insights"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/insightTypes/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/insights"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/insightTypes/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/insights"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*/insightTypes/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/insightTypes/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "billingAccounts/*/locations/*/insightTypes/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "folders/*/locations/*/insightTypes/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "organizations/*/locations/*/insightTypes/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRecommenderV1.ListInsightsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func getInsight(
      request: GetInsightRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Insight {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/insightTypes/"), .singleWildcard,
                .literal("/insights/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/insightTypes/"), .singleWildcard,
                .literal("/insights/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/insightTypes/*/insights/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "billingAccounts/*/locations/*/insightTypes/*/insights/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "folders/*/locations/*/insightTypes/*/insights/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "organizations/*/locations/*/insightTypes/*/insights/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRecommenderV1.Insight.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func markInsightAccepted(
      request: MarkInsightAcceptedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Insight {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markAccepted"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/insightTypes/"), .singleWildcard,
                .literal("/insights/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markAccepted"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markAccepted"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/insightTypes/"), .singleWildcard,
                .literal("/insights/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markAccepted"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/insightTypes/*/insights/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "billingAccounts/*/locations/*/insightTypes/*/insights/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "folders/*/locations/*/insightTypes/*/insights/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard, .literal("/insights/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "organizations/*/locations/*/insightTypes/*/insights/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleCloudRecommenderV1.Insight.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func listRecommendations(
      request: ListRecommendationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.ListRecommendationsResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/recommendations"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/recommendations"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/recommendations"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/recommendations"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*/recommenders/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/recommenders/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "billingAccounts/*/locations/*/recommenders/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "folders/*/locations/*/recommenders/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "organizations/*/locations/*/recommenders/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRecommenderV1.ListRecommendationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func getRecommendation(
      request: GetRecommendationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
                .literal("/recommendations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
                .literal("/recommendations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/recommenders/"), .singleWildcard,
              .literal("/recommendations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "billingAccounts/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "folders/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "organizations/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRecommenderV1.Recommendation.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func markRecommendationDismissed(
      request: MarkRecommendationDismissedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markDismissed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
                .literal("/recommendations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markDismissed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markDismissed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
                .literal("/recommendations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markDismissed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/recommenders/"), .singleWildcard,
              .literal("/recommendations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "billingAccounts/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "folders/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "organizations/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleCloudRecommenderV1.Recommendation.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func markRecommendationClaimed(
      request: MarkRecommendationClaimedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markClaimed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
                .literal("/recommendations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markClaimed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markClaimed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
                .literal("/recommendations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markClaimed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/recommenders/"), .singleWildcard,
              .literal("/recommendations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "billingAccounts/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "folders/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "organizations/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleCloudRecommenderV1.Recommendation.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func markRecommendationSucceeded(
      request: MarkRecommendationSucceededRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markSucceeded"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
                .literal("/recommendations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markSucceeded"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markSucceeded"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
                .literal("/recommendations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markSucceeded"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/recommenders/"), .singleWildcard,
              .literal("/recommendations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "billingAccounts/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "folders/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "organizations/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleCloudRecommenderV1.Recommendation.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func markRecommendationFailed(
      request: MarkRecommendationFailedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.Recommendation {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markFailed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
                .literal("/recommendations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markFailed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markFailed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard,
                .literal("/recommendations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):markFailed"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/recommenders/"), .singleWildcard,
              .literal("/recommendations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "billingAccounts/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("folders/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "folders/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/recommendations/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "organizations/*/locations/*/recommenders/*/recommendations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleCloudRecommenderV1.Recommendation.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func getRecommenderConfig(
      request: GetRecommenderConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/recommenders/*/config"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "name",
            expecting: "organizations/*/locations/*/recommenders/*/config"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/recommenders/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "name",
            expecting: "billingAccounts/*/locations/*/recommenders/*/config"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRecommenderV1.RecommenderConfig.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func updateRecommenderConfig(
      request: UpdateRecommenderConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.RecommenderConfig {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.recommenderConfig.map({ $0.name }),
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/recommenders/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "recommender_config.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.recommenderConfig.map({ $0.name }),
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "recommender_config.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.recommenderConfig.map({ $0.name }),
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/recommenders/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "recommender_config.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.recommenderConfig.map({ $0.name }),
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "recommender_config.name",
            expecting: "projects/*/locations/*/recommenders/*/config"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.recommenderConfig.map({ $0.name }),
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/recommenders/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "recommender_config.name",
            expecting: "organizations/*/locations/*/recommenders/*/config"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.recommenderConfig.map({ $0.name }),
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/recommenders/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "recommender_config.name",
            expecting: "billingAccounts/*/locations/*/recommenders/*/config"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.recommenderConfig {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudRecommenderV1.RecommenderConfig.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func getInsightTypeConfig(
      request: GetInsightTypeConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/insightTypes/*/config"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "name",
            expecting: "organizations/*/locations/*/insightTypes/*/config"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "name",
            expecting: "billingAccounts/*/locations/*/insightTypes/*/config"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRecommenderV1.InsightTypeConfig.self, timeout: options.attemptTimeout
      ).get()
    }

    @concurrent
    public func updateInsightTypeConfig(
      request: UpdateInsightTypeConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRecommenderV1.InsightTypeConfig {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.insightTypeConfig.map({ $0.name }),
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "insight_type_config.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.insightTypeConfig.map({ $0.name }),
              matching: [
                .literal("organizations/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "insight_type_config.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.insightTypeConfig.map({ $0.name }),
              matching: [
                .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
                .singleWildcard, .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
              ],
              fieldName: "insight_type_config.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.insightTypeConfig.map({ $0.name }),
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "insight_type_config.name",
            expecting: "projects/*/locations/*/insightTypes/*/config"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.insightTypeConfig.map({ $0.name }),
            matching: [
              .literal("organizations/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "insight_type_config.name",
            expecting: "organizations/*/locations/*/insightTypes/*/config"
          )
          paths.append(builder.build())
        }
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.insightTypeConfig.map({ $0.name }),
            matching: [
              .literal("billingAccounts/"), .singleWildcard, .literal("/locations/"),
              .singleWildcard, .literal("/insightTypes/"), .singleWildcard, .literal("/config"),
            ],
            fieldName: "insight_type_config.name",
            expecting: "billingAccounts/*/locations/*/insightTypes/*/config"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.insightTypeConfig {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudRecommenderV1.InsightTypeConfig.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
