// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Contains metadata about how much sustainability a recommendation can save or
/// incur.
public struct SustainabilityProjection: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Carbon Footprint generated in kg of CO2 equivalent.
  /// Chose kg_c_o2e so that the name renders correctly in camelCase (kgCO2e).
  public var kgCO2E: Swift.Double = Swift.Double()

  /// Duration for which this sustainability applies.
  public var duration: GoogleCloudWkt.Duration? = nil

  /// Initialize a new instance of `SustainabilityProjection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SustainabilityProjection().with { $0.kgCO2E = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case kgCO2E = "kgCO2e"
    case duration = "duration"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.kgCO2E = try container.decode(Swift.Double.self, forKey: .kgCO2E)
    self.duration = try container.decodeIfPresent(GoogleCloudWkt.Duration.self, forKey: .duration)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.kgCO2E, forKey: .kgCO2E)
    try container.encode(self.duration, forKey: .duration)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.v1.SustainabilityProjection"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
