// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Contains metadata about how much sustainability a recommendation can save or
/// incur.
public struct SustainabilityProjection: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Carbon Footprint generated in kg of CO2 equivalent.
  /// Chose kg_c_o2e so that the name renders correctly in camelCase (kgCO2e).
  public var kgCO2E: Swift.Double = Swift.Double()

  /// Duration for which this sustainability applies.
  public var duration: GoogleWKT.WKTDuration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SustainabilityProjection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SustainabilityProjection().with { $0.kgCO2E = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let kgCO2E = CodingKeys(stringValue: "kgCO2e")
    static let duration = CodingKeys(stringValue: "duration")

    static let _knownKeys: Set<Swift.String> = [
      "kgCO2e",
      "duration",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .kgCO2E) {
      self.kgCO2E = value
    }
    self.duration = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .duration)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.kgCO2E, forKey: .kgCO2E)
    try container.encodeIfPresent(self.duration, forKey: .duration)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `SustainabilityProjection`: `"type.googleapis.com/google.cloud.recommender.v1.SustainabilityProjection"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.v1.SustainabilityProjection"
  }

  /// Initialize an instance of `SustainabilityProjection` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.recommender.v1.SustainabilityProjection"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `SustainabilityProjection` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
