// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Contains various matching options for values for a GCP resource field.
public struct ValueMatcher: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// To be used for full regex matching.
  public var matchVariant: OneOf_MatchVariant? = nil

  /// Initialize a new instance of `ValueMatcher`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ValueMatcher().with { $0.matchesPattern = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case matchesPattern = "matchesPattern"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var matchVariant: OneOf_MatchVariant? = nil
    let matchVariantCheckAndSet = {
      if matchVariant != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'matchVariant'"))
      }
      matchVariant = $0
    }
    if let matchesPattern = try container.decodeIfPresent(
      Swift.String.self, forKey: .matchesPattern)
    {
      try matchVariantCheckAndSet(.matchesPattern(matchesPattern))
    }
    self.matchVariant = matchVariant
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.matchVariant {
      switch choice {
      case .matchesPattern(let value):
        try container.encode(value, forKey: .matchesPattern)
      }
    }
  }

  /// To be used for full regex matching.
  public enum OneOf_MatchVariant: Codable, Equatable, Sendable {
    /// To be used for full regex matching. The regular expression is using the
    /// Google RE2 syntax (https://github.com/google/re2/wiki/Syntax), so to be
    /// used with RE2::FullMatch
    case matchesPattern(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.recommender.v1.ValueMatcher"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
